version: '1.0'
services:
  node:
    image: lobomfz/resume-backend:latest
    ports:
      - '3333:3333'
    environment:
      TOKEN: ${TOKEN}

  react-nginx:
    image: lobomfz/self-building-resume
    volumes:
      - /home/ec2-user/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/ec2-user/conf/lobomfz.com.crt:/etc/ssl/lobomfz.com.crt
      - /home/ec2-user/conf/lobomfz.com.key:/etc/ssl/private/lobomfz.com.key
    network_mode: 'host'
